package main

import (
	fmt "github.com/go-cli-tools/format"
)

func main() {
	_, _ = fmt.Println("Normal")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(fmt.Bold).Println("Bold")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(fmt.Italics).Println("Italics")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(fmt.Light).Println("Light")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(fmt.Underlined).Println("Underlined")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(fmt.Blink).Println("Blink")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(fmt.Inverted).Println("Inverted")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(fmt.Hidden).Println("Hidden")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(fmt.StrikeThrough).Println("StrikeThrough")
	_, _ = fmt.Println("")

	_, _ = fmt.WithColour(fmt.Black).Println("Black")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.Red).Println("Red")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.Green).Println("Green")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.Yellow).Println("Yellow")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.Blue).Println("Blue")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.Magenta).Println("Magenta")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.Cyan).Println("Cyan")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.White).Println("White")
	_, _ = fmt.Println("")

	_, _ = fmt.WithColour(fmt.BrightBlack).Println("Bright Black")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.BrightRed).Println("Bright Red")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.BrightGreen).Println("Bright Green")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.BrightYellow).Println("Bright Yellow")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.BrightBlue).Println("Bright Blue")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.BrightMagenta).Println("Bright Magenta")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.BrightCyan).Println("Bright Cyan")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(fmt.BrightWhite).Println("Bright White")
	_, _ = fmt.Println("")

}
