package main

import (
	fmt "github.com/go-cli-tools/format"
	"github.com/go-cli-tools/format/colour"
	"github.com/go-cli-tools/format/style"
)

func main() {
	_, _ = fmt.Println("Normal")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(style.Bold).Println("Bold")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(style.Italics).Println("Italics")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(style.Light).Println("Light")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(style.Underlined).Println("Underlined")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(style.Blink).Println("Blink")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(style.Inverted).Println("Inverted")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(style.Hidden).Println("Hidden")
	_, _ = fmt.Println("")
	_, _ = fmt.WithStyle(style.StrikeThrough).Println("StrikeThrough")
	_, _ = fmt.Println("")

	_, _ = fmt.WithColour(colour.Black).Println("Black")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.Red).Println("Red")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.Green).Println("Green")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.Yellow).Println("Yellow")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.Blue).Println("Blue")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.Magenta).Println("Magenta")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.Cyan).Println("Cyan")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.White).Println("White")
	_, _ = fmt.Println("")

	_, _ = fmt.WithColour(colour.BrightBlack).Println("Bright Black")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.BrightRed).Println("Bright Red")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.BrightGreen).Println("Bright Green")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.BrightYellow).Println("Bright Yellow")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.BrightBlue).Println("Bright Blue")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.BrightMagenta).Println("Bright Magenta")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.BrightCyan).Println("Bright Cyan")
	_, _ = fmt.Println("")
	_, _ = fmt.WithColour(colour.BrightWhite).Println("Bright White")
	_, _ = fmt.Println("")

	_, _ = fmt.WithBackground(colour.Black).Println("Black")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.Red).Println("Red")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.Green).Println("Green")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.Yellow).Println("Yellow")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.Blue).Println("Blue")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.Magenta).Println("Magenta")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.Cyan).Println("Cyan")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.White).Println("White")
	_, _ = fmt.Println("")

	_, _ = fmt.WithBackground(colour.BrightBlack).Println("Bright Black")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.BrightRed).Println("Bright Red")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.BrightGreen).Println("Bright Green")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.BrightYellow).Println("Bright Yellow")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.BrightBlue).Println("Bright Blue")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.BrightMagenta).Println("Bright Magenta")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.BrightCyan).Println("Bright Cyan")
	_, _ = fmt.Println("")
	_, _ = fmt.WithBackground(colour.BrightWhite).Println("Bright White")
	_, _ = fmt.Println("")

	_, _ = fmt.WithStyle(style.Bold).WithBackground(colour.Red).WithColour(colour.Cyan).Print("Multi")
	_, _ = fmt.WithStyle(style.Italics).WithBackground(colour.Cyan).WithColour(colour.Red).Println("Color")
}
